### ISSUE TITLE
Problems running the installation instructions

### ISSUE THREAD

**Issue by bucko13** [decentralized-identity/ion#17] opened 2019-05-17 21:59 UTC
I've been running into some issues trying to load up an ION node on a VPS. I'll try and list these out and the workarounds I've been using as best I can. I'm running all of this on an instance of Ubuntu 18.04.2 LTS on GCP.

* The first issue was with the zeromq installation. Running from the installation instructions I got the following error, which I was able to get around with the steps laid out [here](https://askubuntu.com/questions/918140/how-to-install-0mq-on-ubuntu-16-04): 
```
The repository 'http://ppa.launchpad.net/chris-lea/zeromq/ubuntu bionic Release' does not have a Release file.
Updating from such a repository can't be done securely, and is therefore disabled by default.
```

* The instructions for creating the symlink are a little off and were causing some issues. Instead of `ln -s sidetree/lib/bitcored-extension ion-bitcore` I think it should be `ln -s ~/sidetree/lib/bitcored-extension ion-bitcore` or `ln -s [ABSOLUTE_PATH_TO_SIDETREE_REPO]/sidetree/lib/bitcored-extension ion-bitcore`

* The first step for configuring ION, when you're supposed to edit `json/bitcoin-config.json`, instead of `http://localhost:3001/ion-bitcore/` it should probably be `http://localhost:3001/insight-api` (no trailing slash) otherwise requests to the bitcore node will fail

* Now after all the above steps and fixes, when the node is fully synced I try and run `npm run build && npm run bitcoin` but I get the following message:

```
Fetching Sidetree transactions after transation 'undefined' from bitcored service...
Response status 'ServerError' when fetching transactions from bitcore.
Waiting for 100 seconds before fetching and processing transactions again.
```
* One thing I found when trying to debug the above is that with the initial bootstrapping requests that are called, the method `handleBlockByHeightRequest` is called and sets up a request to `/blocks/[block height]` but when trying this out with bitcore (and looking at the network requests that insights ui makes), this endpoint doesn't exist. instead `/block-index/[+blockheight]` will return the info that's being looked for (specifically `blockHash`).  

That's about as far as I got. It almost seems like the versions of bitcore aren't lining up but as far as I can tell from the various package.json's in the repo and what I have in my installation, everything seems to be the same. For reference, according to the footer in insights I'm on Insights API v0.4.3

**Comment by jabdov** [comment] 2019-05-23 22:01
Got stuck at the same point. Would be great to get confirmation on the value of the `bitcoreExtensionUri` property in the `json/bitcoin-config.json` and why we are getting a 'ServerError' response status when fetching the transactions from bitcore.

**Comment by thehenrytsai** [comment] 2019-05-24 01:52
We recognize the complexity in getting `bitcored` up and running and have revamped the Sidetree-Bitcoin service so it longer depends on `bitcored` and depends on `bcoin` instead in the [Sidetree repo](https://github.com/decentralized-identity/sidetree).  I will try to propagate this change to ION tomorrow with the appropriate setup guide update, in the mean time you can use [this guide](https://github.com/decentralized-identity/sidetree/tree/master/lib/bitcoin) to kick start `bcoin `setup, which should be much easier than setting up `bitcored`.

**Comment by thehenrytsai** [comment] 2019-05-24 23:01
[Setup guide](https://github.com/decentralized-identity/ion/blob/master/install-guide.md) is updated. Please give it a try!

**Comment by jabdov** [comment] 2019-05-29 10:49
Alright, after the change using the new Sidetree Bitcoin service using `bcoin` instead of `bitcored` and following the new installation guide I managed to setup the ION node with all microservices.
A few things to note:

1. The python dependency is missing in the guide. I had to run `sudo apt-get install -y python`

2. Are there any recommendations to achieve a fast bitcoin peer sync? It took almost 24h to synchronize in my case. At some point, I updated the `bcoin.conf` file to remove the `workers-size` parameter so a default value equal to number of available CPUs would be adopted and noticed syncing going faster. Any guidance would be appreciated.

3. Is it 1000GB storage really needed? I realized the bitcoin testnet blockchain takes less than 40GB. I read that high IOPS help with faster sync, not sure if this is the reason for the current recommendation. If not, 100GB would suffice and we could save some costs.

4. There is no mention of the Sidetree core service REST API available for DID operations in the guide. It would be worth including some reference and examples. In the protocol specification document [https://github.com/decentralized-identity/sidetree/blob/master/docs/protocol.md] in the Sidetree repo, one can find information about the API, however, I am not sure it is fully aligned with the ION implementation. I understood the Sidetree core service API is listening on port 3000. If this is the case, for example, to resolve a DID/DID document, according to the protocol specification, the `<api-version>` in the request path `GET /<api-version>/<did-or-method-name-prefixed-encoded-original-did-document> HTTP/1.1` does not seem to be present in the ION implementation, so the request path that works is:  `GET /<did-or-method-name-prefixed-encoded-original-did-document> HTTP/1.1` on `localhost:3000`.

5. Last, I tried to register a DID document via a POST call to localhost:3000 and got a successful 200 response. Unfortunately, the DID document didn't seem to be registered as I haven't been able to resolve it after a long while neither through the MS ION DID resolve API at [https://beta.discover.did.microsoft.com/1.0/identifiers/] nor though the implemented ION node localhost:3000. When I registered the DID document with the same keys using the MS ION DID create API at [ https://beta.ion.microsoft.com/api/1.0/register/] I got also a successful 200 response, and after a while I was able to resolve the registered DID via both [ https://beta.ion.microsoft.com/api/1.0/register/] and localhost:3000. I know for certain my bitcoin testnet wallet has no balance but I expected an error to pop-up from the bitcoin service advising to fund the wallet but this didn't happen. Should I open this as a separate issue?

6. For whatever reason, I am not able to resolve the DID `did:ion-test:EiD_v05xJjt6GRYvAYpaVe_USS7mhCSh1SYu6O9L-C-p2Q` via localhost:3000 but I am able to do so via [https://beta.discover.did.microsoft.com/1.0/identifiers/]. I noticed my node has a couple of unresolvable transactions in the Mongo database, not sure if this has anything to do. Should I open this as a separate issue?

**Comment by csuwildcat** [comment] 2019-05-31 17:46
@jabdov while @thehenrytsai is on PTO, I can try to answer some of these:

1. Looks like the Python install step is indeed missing from the Guide, so we should get that added - do you want to do a PR for the Guide, or would you rather have me do that?
2. Hmm, 24 hours does seem like a long time for sync, longer than I have seen with my node, but @thehenrytsai or @logangirvin would probably have a better sense of the latest build's expected time-to-sync
3. Having 1TB of storage isn't technically neccessary, but it is the recommended amount for the reason that on mainnet, Bitcoin is ~200GB, and we were hoping folks would have enough room left for storing either full or large majority of the verbose batch data (at least for some decent period of time). You could probably get away with less storage for another year, I would imagine.
4. I am wondering if there is a difference between the generic Sidetree calls and the ION ones (specifically `ion-test`). This is something Henry and Logan will have insight on.
5. This may just be a case of not having the correct return/code path in place for when a wallet does not have the funds to do the actual anchoring of a batch - Logan, Henry, any ideas?
6. This should not happen if the batch data is available. I will follow up with Henry.

**Comment by AlexITC** [comment] 2019-06-01 03:15
Adding some details:
- Bitcoind mainnet database needs 260 GB right now, I have no idea what BCoin database requires
- Only the ION transactions are indexed in mongo, which means that 300 GB should enough for running ION using bitcoin mainnet for a while (assuming that BCoin needs similar space).
- About the missing transactions, you should have seen a log when a transaction is indexed, note that there is a config argument specified the first block to index, see [bitcoin-config.json](https://github.com/decentralized-identity/ion/blob/master/json/bitcoin-config.json#L6).

**Comment by csuwildcat** [comment] 2019-06-01 03:18
Note: Bcoin is radically smaller in total size after sync, because it
doesn't create a bloated DB variant of the core Bitcoin transaction dataset
to facilitate its APIs. This was a major reason for the change.

**Comment by AlexITC** [comment] 2019-06-06 13:36
> NOTE: The latest release of bcoin contains a non-backward compatible change to the rest API. Please read the changelog's "migrating" section for more details.

Regarding bcoin, they claim to have introduced breaking API changes which seem to not be compatible with the bitcoin client.

I get this log while trying to run the client:
```
Getting current block height...
{ FetchError: request to http://localhost:18332/ failed, reason: Parse Error
    at ClientRequest.<anonymous> (/home/ubuntu/ion/node_modules/node-fetch/lib/index.js:1444:11)
    at ClientRequest.emit (events.js:198:13)
    at Socket.socketOnData (_http_client.js:448:9)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:94:17)
  message:
   'request to http://localhost:18332/ failed, reason: Parse Error',
  type: 'system',
  errno: 'HPE_INVALID_CONSTANT',
  code: 'HPE_INVALID_CONSTANT' }
Sidetree-Bitcoin node initialization failed with error: FetchError: request to http://localhost:18332/ failed, reason: Parse Error
```

**Comment by AlexITC** [comment] 2019-06-06 17:56
Turns out I was using the wrong port, which should be the `http-port` from BCoin (18331 following the install guide).

**Comment by jabdov** [comment] 2019-06-10 16:11
> Alright, after the change using the new Sidetree Bitcoin service using `bcoin` instead of `bitcored` and following the new installation guide I managed to setup the ION node with all microservices.
> A few things to note:
> 
> 1. The python dependency is missing in the guide. I had to run `sudo apt-get install -y python`
> 2. Are there any recommendations to achieve a fast bitcoin peer sync? It took almost 24h to synchronize in my case. At some point, I updated the `bcoin.conf` file to remove the `workers-size` parameter so a default value equal to number of available CPUs would be adopted and noticed syncing going faster. Any guidance would be appreciated.
> 3. Is it 1000GB storage really needed? I realized the bitcoin testnet blockchain takes less than 40GB. I read that high IOPS help with faster sync, not sure if this is the reason for the current recommendation. If not, 100GB would suffice and we could save some costs.
> 4. There is no mention of the Sidetree core service REST API available for DID operations in the guide. It would be worth including some reference and examples. In the [protocol specification document](https://github.com/decentralized-identity/sidetree/blob/master/docs/protocol.md) in the Sidetree repo, one can find information about the API, however, I am not sure it is fully aligned with the ION implementation. I understood the Sidetree core service API is listening on port 3000. If this is the case, for example, to resolve a DID/DID document, according to the protocol specification, the `<api-version>` in the request path `GET /<api-version>/<did-or-method-name-prefixed-encoded-original-did-document> HTTP/1.1` does not seem to be present in the ION implementation, so the request path that works is:  `GET /<did-or-method-name-prefixed-encoded-original-did-document> HTTP/1.1` on `localhost:3000`.
> 5. Last, I tried to register a DID document via a POST call to localhost:3000 and got a successful 200 response. Unfortunately, the DID document didn't seem to be registered as I haven't been able to resolve it after a long while neither through the [MS ION DID resolve API](https://beta.discover.did.microsoft.com/1.0/identifiers/) nor though the implemented ION node localhost:3000. When I registered the DID document with the same keys using the [MS ION DID create API](https://beta.ion.microsoft.com/api/1.0/register/) I got also a successful 200 response, and after a while I was able to resolve the registered DID via both [MS ION DID resolve API](https://beta.ion.microsoft.com/api/1.0/identifiers) and localhost:3000. I know for certain my bitcoin testnet wallet has no balance but I expected an error to pop-up from the bitcoin service advising to fund the wallet but this didn't happen. Should I open this as a separate issue?
> 6. For whatever reason, I am not able to resolve the DID `did:ion-test:EiD_v05xJjt6GRYvAYpaVe_USS7mhCSh1SYu6O9L-C-p2Q` via localhost:3000 but I am able to do so via [MS ION DID resolve API](https://beta.discover.did.microsoft.com/1.0/identifiers/). I noticed my node has a couple of unresolvable transactions in the Mongo database, not sure if this has anything to do. Should I open this as a separate issue?

So, in the meantime, I have sorted a few things:

Re 4. I can confirm the APIs implemented do not include the version prefix in their path necessarily.

Re 5. The issue (provided the wallet has funds) is with the API call in the function `getUnspentCoins(address)` of the BitcoinProcessor class, used by the `writeTransaction` function in the same class, to write the hash of the anchor file in the blockchain. This functions calls a BCoin API GET method  `/coin/address/${addressToSearch}` which is not supported by BCoin. I tried to look for the intended method but couldn't find it in the current API specification. The unspent coins could be obtained by processing all transactions associated with a particular address using the GET method ` /tx/address/${addressToSearch}` or perhaps using the BCoin wallet APIs (instead of the node APIs). I was not successful with any of these (someone shout if find a solution) and opted for an external service provided by `chain.so`. Not ideal for production, but could solve the problem for testing. I'll raise a separate issue and am happy to share the code I am using to make it work for now.

Re 6. I solved this issue by stopping all services -except for the BCoin one, deleting the mongo databases, and restarting the services again. It seems that my node got some sync problem at some point and was not able to pick up some DIDs even DIDs created by the same node. I couldn't spot what the problem was but "resetting" the Sidetree node worked.

**Comment by thehenrytsai** [comment] 2019-06-11 22:26
Thanks @jabdov for following up with the issues you faced, will look at issue #23 in detail.
The steps you performed regarding 6 is correct when facing protocol breaking changes.
Closing this issue now.

**Closed by thehenrytsai** 2019-06-11 22:26 UTC
